spring.application.name=Group3
server.port=8081

# The Guardian API Key
guardian.api.key=11d76f4a-649e-4425-b6b3-b5f214d8d0b2


#MongoDB Properties
spring.data.mongodb.uri=mongodb://localhost:27017/Group3DB


elasticsearch.host=localhost
elasticsearch.port=9200

# Disable SSL for Elasticsearch (for local development)
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.socket-timeout=10s
spring.elasticsearch.connection-timeout=5s